name: "Bandit scan"

on: pull_request

permissions: {}

jobs:
  bandit-scan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - id: files
        uses: tj-actions/changed-files@b74df86ccb65173a8e33ba5492ac1a2ca6b216fd # v45.0.7
        with:
          files: |
            **/*.py
            **/*.pyx
            **/*.pyi

      - name: Setup Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.12"

      - name: Run checks
        env:
          CHANGED_FILES: ${{steps.files.outputs.all_changed_files}}
        run: |
          if [[ ! -z "$CHANGED_FILES" ]]; then
            pip install bandit
            echo "Bandit version: "$(bandit --version | head -1)
            echo "The files will be checked: "$(echo "$CHANGED_FILES")
            bandit -a file --ini tox.ini --verbose -r "$CHANGED_FILES"
          else
            echo "No files with the \"py\" extension found"
          fi
