name: Build documentation

on:
  workflow_dispatch: # run on request (no need for PR)

  push:
    branches:
      - main
    paths-ignore:
      - ".github/**" # Ignore changes towards the .github directory

# No permissions by default
permissions: {}

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.12

      - name: Install package with dev, notebooks and docs requirements
        run: |
          pip install ".[dev,notebooks]" --pre
          pip install -r requirements/requirements-docs.txt

      - name: Build sphinx documentation
        # We build twice to ensure that all references are resolved
        run: |
          cd docs
          make html
          make html
          cd ..

      - name: Clean up repo directory
        run: |
          mkdir -p /tmp/docs_build
          cp -r docs/build/html/* /tmp/docs_build
          rm -rf ./*
          # git fetch && git pull
          # git checkout gh-pages
          cp -r /tmp/docs_build/* ./
          rm -rf /tmp/docs_build
          touch .nojekyll
          # git config --local user.email "action@github.com"
          # git config --local user.name "GitHub Action"
          # git add .
          # git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5
        with:
          # Upload entire repository
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
