name: Build and publish package

on:
  workflow_call: # Make workflow reusable
    inputs:
      enable_dev_dependencies:
        required: false
        type: string
      runner:
        required: true
        type: string
    secrets:
      PYPI_USER:
        required: true
      PYPI_PASSWORD:
        required: true
      PYPI_HOST:
        required: true

env:
  PYPI_USER: ${{ secrets.PYPI_USER }}
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  PYPI_HOST: ${{ secrets.PYPI_HOST }}
  ENABLE_DEV_DEPENDENCIES: ${{ inputs.enable_dev_dependencies }}

permissions:
  contents: read

jobs:
  build_sdk:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout code with caching for Git LFS
        uses: nschloe/action-cached-lfs-checkout@f46300cd8952454b9f0a21a3d133d4bd5684cfc2 # v1.2.3

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: 3.12

      - name: Install package with dev and notebook requirements
        run: |
          python -m pip install --upgrade pip

          if [[ $ENABLE_DEV_DEPENDENCIES = 1 ]]; then
          pip install ".[dev,notebooks]" --pre
          else
          pip install ".[dev,notebooks]"
          fi

      - name: Install build tools
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Check package contents
        run: twine check dist/*

      - name: Upload wheel and source files as github artifact
        # Publish the built wheel and source tarball to github
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ always() }}
        with:
          name: geti_sdk
          path: dist

      - name: Publish SDK package to pypi
        run: |
          if [[ $PYPI_HOST = "test.pypi.org" ]]; then
            twine upload -r testpypi dist/* -u $PYPI_USER -p $PYPI_PASSWORD
          else
            twine upload dist/* -u $PYPI_USER -p $PYPI_PASSWORD
          fi


      - name: Clean up dist directory if it was created
        if: ${{ always() }}
        run: |
          if OUTPUT=$(ls | grep -c dist)
          then
            echo "Cleaning up dist directory"
            rm -r dist
          fi
