name: Record and push VCR cassettes

on:
  ## When run on comment creation (in PRs) it is not clear how to find the reference branch
  # issue_comment:
  #   types: [created]
  workflow_dispatch:  # run on request (no need for PR)

env:
  # Python version
  PYTHON_VERSION: 3.9

  # Other environment variables used in the tests
  TEST_MODE: "RECORD"
  REPORT_DIRECTORY: reports
  VIRTUALENV_DIRECTORY: .venv

permissions:
  contents: write
  pull-requests: write  # 'write' access to pull requests

jobs:
  recording_integration_tests:
    # if: contains(github.event.comment.body, '/record')

    strategy:
      matrix:
        include:
          - geti_platform_version: "LEGACY"
            host-name: "GETI_HOST"
          - geti_platform_version: "DEVELOP"
            host-name: "GETI_DEVELOP_HOST"

    runs-on: [self-hosted, sdk-runner]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install package with dev requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          python -m virtualenv $VIRTUALENV_DIRECTORY
          source $VIRTUALENV_DIRECTORY/bin/activate
          pip install ".[dev]"

      - name: Record integration test cassettes
        # Proxy settings have to be configured and GETI_HOST set to full address before
        # tests can run
        #
        # NOTE: This step executes all tests in the `tests` directory in `RECORD` mode
        run: |
          export no_proxy=$GETI_HOST,$no_proxy
          export NO_PROXY=$GETI_HOST,$NO_PROXY
          export GETI_HOST=https://$${{ matrix.host-name }}

          pytest tests/pre-merge/integration --html=$REPORT_DIRECTORY/integration_test_report.html --self-contained-html
        env:
          # Login details for the Geti instance to run the tests against
          # Secrets are configured on the repository level (Settings > Secrets)
          GETI_HOST: ${{ secrets.GETI_HOST }}
          GETI_DEVELOP_HOST: ${{ secrets.GETI_DEVELOP_HOST }}

          GETI_USERNAME: ${{ secrets.GETI_USERNAME }}
          GETI_PASSWORD: ${{ secrets.GETI_PASSWORD }}

          GETI_PLATFORM_VERSION: ${{ matrix.geti_platform_version }}

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add tests/fixtures/cassettes
          git commit -m "Update VCR cassettes"
          git fetch

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}

      - name: Upload test reports
        # Publish the test reports to GitHub
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-reports
          path: ${{ env.REPORT_DIRECTORY }}

      - name: Clean up artifact and venv directories
        # Remove temporary report directory
        if: ${{ always() }}
        run: |
          rm -rf $REPORT_DIRECTORY $VIRTUALENV_DIRECTORY
