name: "Workflows static analysis"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - "releases/**"
  pull_request:
    branches: ["*"]
    paths:
      - ".github/**"
env:
  ZIZMOR_VERSION: 1.5.2

permissions: {}

jobs:
  zizmor-scan-full:
    # Run on schedule, workflow_dispatch or push, all severity, publish results into Security tab (reporting)
    # Skip Dependabot to avoid permission issues.
    if:
      ((github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || github.event_name == 'push' || github.event.pull_request.merged == true)
      && github.actor != 'dependabot[bot]')
    name: Check workflows with zizmor
    permissions:
      contents: read
      security-events: write # to upload issues into security tab
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5.4.0
      - name: Run zizmor
        run: uvx zizmor=="$ZIZMOR_VERSION" . --format sarif --config .github/zizmor.yaml > results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@9e8d0789d4a0fa9ceb6b1738f7e269594bdd67f0 # v3.28.8
        with:
          sarif_file: results.sarif
          category: zizmor

  zizmor-scan-pr:
    # Run only within Pull Requests, fail on high severity and high confidence
    if: (github.event_name == 'pull_request')
    name: Check PR with zizmor
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5.4.0
      - name: Run zizmor
        run: uvx zizmor=="$ZIZMOR_VERSION" . --min-confidence high --min-severity high --config .github/zizmor.yaml
